# Generated by Django 4.2.2 on 2024-07-11 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FootballMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_date", models.DateTimeField()),
                ("team_a", models.CharField(max_length=100)),
                ("team_b", models.CharField(max_length=100)),
                ("match_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("team_a_goal", models.IntegerField(default=0)),
                ("team_b_goal", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FootballTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                (
                    "attack_score",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "defence_score",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "strategy_score",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "perf_score",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                ("desc_en", models.TextField(blank=True)),
                ("desc_cn", models.TextField(blank=True)),
                ("team_logos", models.ImageField(blank=True, upload_to="team_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Marksix_hist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Draw", models.CharField(max_length=255)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserTips_my",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_date", models.DateField()),
                ("race_no", models.IntegerField()),
                ("horse_no", models.IntegerField()),
                ("horse_name", models.CharField(max_length=50)),
                ("hit", models.IntegerField()),
                ("dividend", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_date", models.DateField()),
                ("race_no", models.IntegerField()),
                ("horse_no", models.IntegerField()),
                ("horse_name", models.CharField(max_length=50)),
                ("hit", models.IntegerField()),
                ("dividend", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserScores_my",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("total_hits", models.IntegerField(default=0)),
                ("total_dividend", models.FloatField(default=0)),
                ("hit_weight", models.FloatField(default=0)),
                ("div_weight", models.FloatField(default=0)),
                ("stars", models.CharField(max_length=25, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_my",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("total_hits", models.IntegerField(default=0)),
                ("total_dividend", models.FloatField(default=0)),
                ("hit_weight", models.FloatField(default=0)),
                ("div_weight", models.FloatField(default=0)),
                ("stars", models.CharField(max_length=25, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marksix_user_rec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField()),
                ("Draw", models.CharField(max_length=10)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
                ("Hit", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marksix_rec",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="static/")),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("tw", "Chinese")], max_length=2
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
