# Generated by Django 4.2.2 on 2024-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("race_date", models.DateField()),
                ("race_no", models.IntegerField()),
                ("h1_choice", models.CharField(max_length=50)),
                ("h2_choice", models.CharField(max_length=50)),
                ("h3_choice", models.CharField(max_length=50)),
                ("hit", models.IntegerField()),
            ],
        ),
    ]
