# Generated by Django 4.2.2 on 2025-01-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HorseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_name", models.CharField(max_length=100)),
                ("horse_name_cn", models.CharField(max_length=100)),
                ("band_no", models.CharField(max_length=20, unique=True)),
                ("rating", models.IntegerField()),
                ("rate_change", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LottoTrioSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Search_date", models.DateField()),
                ("Draw", models.CharField(max_length=255)),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("Diff_days", models.IntegerField(default=0)),
                ("Freq", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Marksix_hist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Draw", models.CharField(max_length=255)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TW_lotto_hist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Draw", models.CharField(max_length=255)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_date", models.DateField()),
                ("race_no", models.IntegerField()),
                ("rank", models.IntegerField(default=0)),
                ("jockey_score", models.IntegerField(default=0)),
                ("trainer_score", models.IntegerField(default=0)),
                ("horse_no", models.IntegerField()),
                ("horse_name", models.CharField(max_length=50)),
                ("horse_name_cn", models.CharField(max_length=50, null=True)),
                ("jockey", models.CharField(max_length=25, null=True)),
                ("trainer", models.CharField(max_length=25, null=True)),
                ("hit", models.IntegerField()),
                ("dividend", models.FloatField(default=0)),
                ("ratio", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserScores_my",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("total_hits", models.IntegerField(default=0)),
                ("total_dividend", models.FloatField(default=0)),
                ("hit_weight", models.FloatField(default=0)),
                ("div_weight", models.FloatField(default=0)),
                ("stars", models.CharField(max_length=25, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_my",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("total_hits", models.IntegerField(default=0)),
                ("total_dividend", models.FloatField(default=0)),
                ("hit_weight", models.FloatField(default=0)),
                ("div_weight", models.FloatField(default=0)),
                ("stars", models.CharField(max_length=25, null=True)),
                ("stars1", models.IntegerField(default=0)),
                ("stars2", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race_hist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("place", models.IntegerField()),
                ("date", models.DateField()),
                ("track", models.CharField(max_length=100)),
                ("distance", models.IntegerField()),
                ("good", models.CharField(max_length=100)),
                ("race_class", models.CharField(max_length=100)),
                ("draw", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("trainer", models.CharField(max_length=100)),
                ("jockey", models.CharField(max_length=100)),
                ("lbw", models.CharField(max_length=50)),
                ("win_odds", models.FloatField()),
                ("act_wt", models.IntegerField()),
                ("running_pos", models.CharField(max_length=100)),
                ("finish_time", models.CharField(max_length=50)),
                ("declar_horse_wt", models.IntegerField()),
                ("gear", models.CharField(max_length=50)),
                (
                    "band_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racecard.horseinfo",
                        to_field="band_no",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marksix_user_rec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField()),
                ("Draw", models.CharField(max_length=10)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
                ("Hit", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marksix_rec",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="racecard/images/")),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("tw", "Chinese")], max_length=2
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
