# Generated by Django 4.2.2 on 2024-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
