# Generated by Django 4.2.2 on 2024-01-24 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertips",
            old_name="h1_choice",
            new_name="horse_name",
        ),
        migrations.RemoveField(
            model_name="usertips",
            name="h2_choice",
        ),
        migrations.RemoveField(
            model_name="usertips",
            name="h3_choice",
        ),
    ]
