# Generated by Django 4.2.2 on 2025-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lottotriosearch",
            name="Freq",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
