# Generated by Django 4.2.2 on 2024-07-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0002_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
