# Generated by Django 4.2.2 on 2025-01-06 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0002_alter_lottotriosearch_freq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lottotriosearch",
            name="Freq",
        ),
    ]
