# Generated by Django 4.2.2 on 2025-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0003_remove_lottotriosearch_freq"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottotriosearch",
            name="Freq",
            field=models.IntegerField(default=0),
        ),
    ]
