# Generated by Django 4.2.2 on 2024-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0003_article_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("tw", "Chinese")],
                default="TW",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
