# Generated by Django 4.2.2 on 2024-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0004_article_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.CharField(default="HorseHeadBanner2.jpeg", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
