# Generated by Django 4.2.2 on 2024-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0005_article_image_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscores",
            name="total_dividend",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="usertips",
            name="dividend",
            field=models.FloatField(default=0),
        ),
    ]
