# Generated by Django 4.2.2 on 2025-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0005_racecomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
