# Generated by Django 4.2.2 on 2024-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0005_alter_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_name", models.CharField(max_length=100)),
                ("horse_name_cn", models.CharField(max_length=100)),
                ("band_no", models.CharField(max_length=50)),
                ("rating", models.IntegerField()),
                ("rate_change", models.IntegerField()),
            ],
        ),
    ]
