# Generated by Django 4.2.2 on 2024-07-20 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0006_horseinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horseinfo",
            name="band_no",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_name", models.CharField(max_length=100)),
                ("index", models.IntegerField()),
                ("place", models.IntegerField()),
                ("date", models.DateField()),
                ("track", models.CharField(max_length=100)),
                ("distance", models.IntegerField()),
                ("good", models.CharField(max_length=100)),
                ("race_class", models.CharField(max_length=100)),
                ("draw", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("trainer", models.CharField(max_length=100)),
                ("jockey", models.CharField(max_length=100)),
                ("lbw", models.CharField(max_length=50)),
                ("win_odds", models.FloatField()),
                ("act_wt", models.IntegerField()),
                ("running_pos", models.CharField(max_length=100)),
                ("finish_time", models.CharField(max_length=50)),
                ("declar_horse_wt", models.IntegerField()),
                ("gear", models.CharField(max_length=50)),
                (
                    "band_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racecard.horseinfo",
                        to_field="band_no",
                    ),
                ),
            ],
        ),
    ]
