# Generated by Django 4.2.2 on 2024-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0006_userscores_total_dividend_usertips_dividend"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscores",
            name="div_weight",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userscores",
            name="hit_weight",
            field=models.FloatField(default=0),
        ),
    ]
