# Generated by Django 4.2.2 on 2024-07-20 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0007_alter_horseinfo_band_no_race"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Race",
            new_name="Race_hist",
        ),
    ]
