# Generated by Django 4.2.2 on 2025-01-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0007_alter_race_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="racecomment",
            name="race_date",
            field=models.DateField(null=True),
        ),
    ]
