# Generated by Django 4.2.2 on 2024-07-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0008_rename_race_race_hist"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksix_hist",
            name="NextDraw_date",
            field=models.DateField(null=True),
        ),
    ]
