# Generated by Django 4.2.2 on 2025-02-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0008_racecomment_race_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("stock_code", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
