# Generated by Django 4.2.2 on 2024-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0008_article_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscores",
            name="stars",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
