# Generated by Django 4.2.2 on 2025-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0009_stockinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockinfo",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("tw", "Chinese")],
                default="tw",
                max_length=2,
            ),
        ),
    ]
