# Generated by Django 4.2.2 on 2024-07-20 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0009_marksix_hist_nextdraw_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race_hist",
            name="horse_name",
        ),
    ]
