# Generated by Django 4.2.2 on 2024-03-30 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("racecard", "0009_userscores_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTips_my",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_date", models.DateField()),
                ("race_no", models.IntegerField()),
                ("horse_no", models.IntegerField()),
                ("horse_name", models.CharField(max_length=50)),
                ("hit", models.IntegerField()),
                ("dividend", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserScores_my",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("total_hits", models.IntegerField(default=0)),
                ("total_dividend", models.FloatField(default=0)),
                ("hit_weight", models.FloatField(default=0)),
                ("div_weight", models.FloatField(default=0)),
                ("stars", models.CharField(max_length=25, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_my",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
