# Generated by Django 4.2.2 on 2025-02-24 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("racecard", "0010_stockinfo_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="topics",
            field=models.CharField(default="Horse", max_length=15),
        ),
        migrations.AlterField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                default="Monkey",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
