# Generated by Django 4.2.2 on 2024-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0010_remove_race_hist_horse_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TW_lotto_hist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Draw", models.CharField(max_length=255)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
                ("NextDraw_date", models.DateField(null=True)),
            ],
        ),
    ]
