# Generated by Django 4.2.2 on 2024-06-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("racecard", "0011_marksix_hist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marksix_user_rec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField()),
                ("Draw", models.CharField(max_length=10)),
                ("Date", models.DateField()),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("No4", models.IntegerField()),
                ("No5", models.IntegerField()),
                ("No6", models.IntegerField()),
                ("No7", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marksix_rec",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
