# Generated by Django 4.2.2 on 2025-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0011_article_topics_alter_article_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marksix_user_rec",
            old_name="Hit",
            new_name="Hit35",
        ),
        migrations.RemoveField(
            model_name="marksix_user_rec",
            name="No7",
        ),
        migrations.AddField(
            model_name="marksix_user_rec",
            name="Hit4",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marksix_user_rec",
            name="Hit45",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marksix_user_rec",
            name="Hit5",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marksix_user_rec",
            name="Hit55",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marksix_user_rec",
            name="Hit6",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="marksix_user_rec",
            name="Draw",
            field=models.CharField(default="NA", max_length=10),
        ),
    ]
