# Generated by Django 4.2.2 on 2024-05-28 15:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0011_marksix_hist"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "secret_info",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=100)
                    ),
                ),
            ],
        ),
    ]
