# Generated by Django 4.2.2 on 2024-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0011_tw_lotto_hist"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="ratio",
            field=models.IntegerField(default=0),
        ),
    ]
