# Generated by Django 4.2.2 on 2024-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0012_marksix_user_rec"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootballTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("attack_scores", models.PositiveSmallIntegerField()),
                ("defence_scores", models.PositiveSmallIntegerField()),
                ("strategy_scores", models.PositiveSmallIntegerField()),
                ("perf_score", models.PositiveSmallIntegerField()),
                ("attack_desc_en", models.TextField(blank=True)),
                ("attack_desc_cn", models.TextField(blank=True)),
                ("defence_desc_en", models.TextField(blank=True)),
                ("defence_desc_cn", models.TextField(blank=True)),
                ("strategy_desc_en", models.TextField(blank=True)),
                ("strategy_desc_cn", models.TextField(blank=True)),
                ("perf_desc_en", models.TextField(blank=True)),
                ("perf_desc_cn", models.TextField(blank=True)),
                ("team_logos", models.ImageField(blank=True, upload_to="team_logos/")),
            ],
        ),
    ]
