# Generated by Django 4.2.2 on 2024-09-15 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("racecard", "0013_userscores_stars1_userscores_stars2"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTips_jc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_date", models.DateField()),
                ("race_no", models.IntegerField()),
                ("horse_no", models.IntegerField()),
                ("horse_name", models.CharField(max_length=50)),
                ("jockey_name", models.CharField(max_length=50)),
                ("hit", models.IntegerField()),
                ("dividend", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserTips_my",
        ),
    ]
