# Generated by Django 4.2.2 on 2025-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0013_rename_hit35_marksix_user_rec_hit1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscores",
            name="stars",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="userscores_my",
            name="stars",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
