# Generated by Django 4.2.2 on 2024-06-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0013_footballteam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footballteam",
            name="attack_scores",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="defence_scores",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="strategy_scores",
        ),
        migrations.AddField(
            model_name="footballteam",
            name="attack_score",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="footballteam",
            name="defence_score",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="footballteam",
            name="strategy_score",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="footballteam",
            name="perf_score",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
