# Generated by Django 4.2.2 on 2024-09-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0014_usertips_jc_delete_usertips_my"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertips_jc",
            old_name="horse_no",
            new_name="score",
        ),
        migrations.RemoveField(
            model_name="usertips_jc",
            name="horse_name",
        ),
        migrations.RemoveField(
            model_name="usertips_jc",
            name="race_no",
        ),
        migrations.AlterField(
            model_name="usertips_jc",
            name="hit",
            field=models.IntegerField(default=0),
        ),
    ]
