# Generated by Django 4.2.2 on 2024-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0014_remove_footballteam_attack_scores_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootballMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_date", models.DateTimeField()),
                ("team_a", models.CharField(max_length=100)),
                ("team_b", models.CharField(max_length=100)),
                ("match_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
            ],
        ),
    ]
