# Generated by Django 4.2.2 on 2025-05-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0014_alter_userscores_stars_alter_userscores_my_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="win_flag",
            field=models.BooleanField(default=False),
        ),
    ]
