# Generated by Django 4.2.2 on 2024-09-15 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0015_rename_horse_no_usertips_jc_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertips_jc",
            old_name="jockey_name",
            new_name="jockey",
        ),
    ]
