# Generated by Django 4.2.2 on 2024-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0015_footballmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="footballmatch",
            name="team_a_goal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="footballmatch",
            name="team_b_goal",
            field=models.IntegerField(default=0),
        ),
    ]
