# Generated by Django 4.2.2 on 2025-05-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0015_usertips_win_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="win_div",
            field=models.FloatField(default=0),
        ),
    ]
