# Generated by Django 4.2.2 on 2025-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0016_usertips_win_div"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksix_user_rec",
            name="No7",
            field=models.IntegerField(default=0),
        ),
    ]
