# Generated by Django 4.2.2 on 2024-07-01 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0016_footballmatch_team_a_goal_footballmatch_team_b_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footballteam",
            old_name="attack_desc_cn",
            new_name="desc_cn",
        ),
        migrations.RenameField(
            model_name="footballteam",
            old_name="attack_desc_en",
            new_name="desc_en",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="defence_desc_cn",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="defence_desc_en",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="perf_desc_cn",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="perf_desc_en",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="strategy_desc_cn",
        ),
        migrations.RemoveField(
            model_name="footballteam",
            name="strategy_desc_en",
        ),
    ]
