# Generated by Django 4.2.2 on 2024-09-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0016_rename_jockey_name_usertips_jc_jockey"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="jockey",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
