# Generated by Django 4.2.2 on 2024-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0017_rename_attack_desc_cn_footballteam_desc_cn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksix_user_rec",
            name="Hit",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
