# Generated by Django 4.2.2 on 2025-11-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0017_marksix_user_rec_no7"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksix_hist",
            name="Price1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marksix_hist",
            name="Price2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marksix_hist",
            name="Price3",
            field=models.IntegerField(default=0),
        ),
    ]
