# Generated by Django 4.2.2 on 2024-09-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0017_usertips_jockey"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
