# Generated by Django 4.2.2 on 2024-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0018_usertips_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="jockey_score",
            field=models.IntegerField(default=0),
        ),
    ]
