# Generated by Django 4.2.2 on 2025-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0018_marksix_hist_price1_marksix_hist_price2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marksix_hist",
            name="next_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="marksix_hist",
            name="next_draw",
            field=models.CharField(default="NA", max_length=255),
        ),
        migrations.AlterField(
            model_name="marksix_hist",
            name="Price1",
            field=models.CharField(default="NA", max_length=30),
        ),
        migrations.AlterField(
            model_name="marksix_hist",
            name="Price2",
            field=models.CharField(default="NA", max_length=30),
        ),
        migrations.AlterField(
            model_name="marksix_hist",
            name="Price3",
            field=models.CharField(default="NA", max_length=30),
        ),
    ]
