# Generated by Django 4.2.2 on 2024-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0018_marksix_user_rec_hit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksix_user_rec",
            name="Hit",
            field=models.IntegerField(default=0),
        ),
    ]
