# Generated by Django 4.2.2 on 2024-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0019_usertips_jockey_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="trainer",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="usertips",
            name="trainer_score",
            field=models.IntegerField(default=0),
        ),
    ]
