# Generated by Django 4.2.2 on 2025-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0019_marksix_hist_next_date_marksix_hist_next_draw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksix_hist",
            name="Price1",
            field=models.CharField(default="NA", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="marksix_hist",
            name="Price2",
            field=models.CharField(default="NA", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="marksix_hist",
            name="Price3",
            field=models.CharField(default="NA", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="marksix_hist",
            name="next_draw",
            field=models.CharField(default="NA", max_length=255, null=True),
        ),
    ]
