# Generated by Django 4.2.2 on 2024-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0020_usertips_trainer_usertips_trainer_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertips",
            name="horse_name_cn",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
