# Generated by Django 4.2.2 on 2024-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0022_delete_footballmatch_delete_footballteam_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LottoTrioSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Search_date", models.DateField()),
                ("Draw", models.CharField(max_length=255)),
                ("No1", models.IntegerField()),
                ("No2", models.IntegerField()),
                ("No3", models.IntegerField()),
                ("Diff_days", models.IntegerField()),
            ],
        ),
    ]
