# Generated by Django 4.2.2 on 2025-01-04 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0023_lottotriosearch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tw_lotto_hist",
            name="NextDraw_date",
        ),
    ]
