# Generated by Django 4.2.2 on 2025-01-04 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("racecard", "0024_remove_tw_lotto_hist_nextdraw_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marksix_hist",
            name="NextDraw_date",
        ),
    ]
